# Generated by Django 2.1.2 on 2018-10-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='Food_Price',
            field=models.FloatField(),
        ),
    ]
