# Generated by Django 2.1.2 on 2018-10-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_auto_20181028_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='Food_Name',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
