# Generated by Django 2.1.2 on 2018-10-28 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_auto_20181028_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='Food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.Food_items'),
        ),
    ]
